# Numpy Basic

In [3]:
import numpy as np

### 기본 내장 함수

In [2]:
arr = np.array([1, 2, 3]) # np.array를 리스트에 적용하면 array로 변환할 수 있음.

In [3]:
arr

array([1, 2, 3])

In [4]:
arr = np.arange(10) # 내장함수 range()에 대응하는 함수로, 이에 해당하는 array를 반환.

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((5, 7)) # 튜플로 지정된 shape를 갖는 0으로 가득찬 array를 반환.

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((5, 7)) # 이건 1로 채워진 array 반환.

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.full((2, 3), 5) # 인자로 shape 튜플, value를 받으며, 이에 따라 해당 shape이며 value로 채워진 array 반환.

array([[5, 5, 5],
       [5, 5, 5]])

In [9]:
np.eye(3) # n*n 크기의 Identity Matirx 반환.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
tmp = np.random.randint(0, 3, size=(6,6)) # 0 이상 3 미만인 정수를 랜덤으로 배정한 6*6 array 반환

In [11]:
tmp

array([[1, 2, 1, 0, 0, 1],
       [1, 1, 2, 1, 2, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 1, 2, 0, 0, 2],
       [0, 2, 1, 2, 2, 1],
       [0, 0, 2, 2, 2, 1]])

### Array의 매서드

In [12]:
tmp.reshape((4, 9)) # (4, 9) shape를 갖는 array로 변형하는 매서드 -- 단 이걸 사용해도 tmp는 불변!

array([[1, 2, 1, 0, 0, 1, 1, 1, 2],
       [1, 2, 1, 0, 1, 0, 1, 0, 0],
       [0, 1, 2, 0, 0, 2, 0, 2, 1],
       [2, 2, 1, 0, 0, 2, 2, 2, 1]])

In [13]:
tmp.reshape((-1,3)) # 하나의 차원을 -1로 해두면, array의 size에 맞추어 알아서 조정해 줌.

array([[1, 2, 1],
       [0, 0, 1],
       [1, 1, 2],
       [1, 2, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 2],
       [0, 0, 2],
       [0, 2, 1],
       [2, 2, 1],
       [0, 0, 2],
       [2, 2, 1]])

In [14]:
tmp.ndim # Number of Array Dimensions를 반환

2

In [15]:
tmp.size # Array의 Entry 개수를 반환

36

In [16]:
tmp.shape # Array의 Shape를 반환

(6, 6)

### Array의 인덱싱 및 슬라이싱

In [17]:
tmp[1, 1] # Array의 인덱싱은 [x][y].. 형태 대신 [x, y,..]로!

1

In [18]:
tmp[0:2, 1:3] # 슬라이싱도 마찬가지!

array([[2, 1],
       [1, 2]])

In [19]:
bool_idx = np.random.randint(0, 2, (6, 6), dtype = bool) # 임의의 6*6 Boolean Array를 만듦.

In [20]:
bool_idx

array([[False, False, False,  True, False, False],
       [False, False, False,  True, False, False],
       [ True,  True,  True, False,  True, False],
       [False, False,  True, False, False, False],
       [ True,  True, False, False,  True, False],
       [False,  True,  True,  True,  True, False]])

In [21]:
tmp[bool_idx] # 이 Array를 Index로 넣으면, True에 해당하는 자리의 원소들만 반환됨!

array([0, 1, 0, 1, 0, 0, 2, 0, 2, 2, 0, 2, 2, 2])

In [22]:
tmp == 2 # Array에 조건 연산자를 적용한 조건문을 만들면, 해당 조건이 참인 원소들만 True인 Array가 반환됨.

array([[False,  True, False, False, False, False],
       [False, False,  True, False,  True, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False,  True,  True, False],
       [False, False,  True,  True,  True, False]])

In [23]:
tmp[tmp == 2] # 이렇게 하면 당연히 2인 원소들만 반환될 것.

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Array의 연산

In [24]:
tmp2 = np.random.randint(0, 3, size=(6,6)) # 0 이상 3 미만인 정수를 랜덤으로 배정한 6*6 array 하나 더 만듦.

In [25]:
tmp + tmp2 # element-wise로 사칙연산 가능합니다.

array([[1, 4, 2, 2, 0, 3],
       [2, 2, 4, 3, 4, 1],
       [2, 3, 2, 3, 0, 2],
       [1, 1, 2, 2, 0, 4],
       [1, 2, 2, 3, 2, 3],
       [0, 2, 4, 2, 2, 3]])

In [26]:
tmp * tmp2

array([[0, 4, 1, 0, 0, 2],
       [1, 1, 4, 2, 4, 0],
       [0, 2, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 1, 2, 0, 2],
       [0, 0, 4, 0, 0, 2]])

In [27]:
tmp + 1 # Scalar에 대한 사칙연산도 가능!

array([[2, 3, 2, 1, 1, 2],
       [2, 2, 3, 2, 3, 2],
       [1, 2, 1, 2, 1, 1],
       [1, 2, 3, 1, 1, 3],
       [1, 3, 2, 3, 3, 2],
       [1, 1, 3, 3, 3, 2]])

In [28]:
tmp * 100

array([[100, 200, 100,   0,   0, 100],
       [100, 100, 200, 100, 200, 100],
       [  0, 100,   0, 100,   0,   0],
       [  0, 100, 200,   0,   0, 200],
       [  0, 200, 100, 200, 200, 100],
       [  0,   0, 200, 200, 200, 100]])

In [29]:
np.dot(tmp, tmp2) # 행렬 곱은 dot() 함수 활용!

array([[ 4,  8,  9,  8,  4,  6],
       [ 8,  9, 11, 12,  2, 14],
       [ 2,  1,  2,  4,  2,  2],
       [ 5,  9, 10,  6,  2,  8],
       [ 8,  6, 10, 12,  4, 12],
       [ 8,  6,  8, 10,  0, 14]])

### np.sum() 함수

In [4]:
arrn = np.array([[[8, 6, 7], [9, 8, 7], [5, 1, 6], [2, 9, 7]], # 3차원의 Array를 정의해봅니다.
                 [[6, 8, 1], [1, 2, 3], [7, 0, 2], [4, 0, 9]]])

In [31]:
np.sum(arrn, axis = 0) # 0번 째 인덱스를 제외한 나머지 인덱스들이 같은 것끼리 합해서 반환함.

array([[14, 14,  8],
       [10, 10, 10],
       [12,  1,  8],
       [ 6,  9, 16]])

In [32]:
np.sum(arrn, axis = 1)

array([[24, 24, 27],
       [18, 10, 15]])

In [33]:
np.sum(arrn, axis = 2) # arrn은 2*4*3의 Array인데, 마지막을 제외한 나머지 인덱스들을 기준으로 합의 결과 도출되므로, 2*4의 array가 반환.

array([[21, 24, 12, 18],
       [15,  6,  9, 13]])

### np.append() & np.delete() 함수

In [12]:
arrn

array([[[8, 6, 7],
        [9, 8, 7],
        [5, 1, 6],
        [2, 9, 7]],

       [[6, 8, 1],
        [1, 2, 3],
        [7, 0, 2],
        [4, 0, 9]]])

In [11]:
arrn.shape

(2, 4, 3)

In [34]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0) # 0번 째 축을 기준으로 데이터를 추가하고자 할 때!

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.append(arrn, [[[1, 2, 3]], [[4, 5, 6]]], axis=1)

array([[[8, 6, 7],
        [9, 8, 7],
        [5, 1, 6],
        [2, 9, 7],
        [1, 2, 3]],

       [[6, 8, 1],
        [1, 2, 3],
        [7, 0, 2],
        [4, 0, 9],
        [4, 5, 6]]])

In [13]:
np.delete(arrn, 1, 0) # 0번 째 축의 1번 째 array를 날림

array([[[8, 6, 7],
        [9, 8, 7],
        [5, 1, 6],
        [2, 9, 7]]])